[env]
EM_CACHE = { value = "target/emscripten-cache", relative = true }
EMCC_CFLAGS = "-sSUPPORT_LONGJMP=wasm"

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C",
    "link-arg=-sALLOW_MEMORY_GROWTH=1",
    "-C",
    "link-arg=-sINVOKE_RUN=0",
]
